export const dictionnary = {
    nonPast: "présent",
    past: "passé",
    adverb: "adverbe",
    affirmative: "+",
    negative: "-",
    baseWord: "MOT DE BASE",
    suruForm: "FORME VERBALE AVEC SURU",
    stem: "STEM",
    verbForm: "FORME VERBALE",
    stemUsedIn: "MOTS QUI UTILISENT SON STEM",
    stemTakenFrom: "STEM UTILISÉ",
    wordUsedIn: "MOTS QUI L'UTILISENT",
    wordTakenFrom: "MOTS UTILISÉS",
}